plugins { id 'com.android.application' }
android {
    namespace 'mg.kajypay.gateway'
    compileSdk 34
    defaultConfig {
        applicationId "mg.kajypay.gateway"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "0.1.0"
    }
    buildFeatures { buildConfig true }
    buildTypes { release { minifyEnabled false } }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
