plugins { id 'com.android.application' }
android {
    namespace 'mg.kajypay.gateway'
    compileSdk 34
    defaultConfig {
        applicationId "mg.kajypay.gateway"
        minSdk 24
        targetSdk 34
        versionCode 18
        versionName "0.9.4"
    }
    buildFeatures { buildConfig true }
    signingConfigs {
        stable {
            storeFile file(System.getenv("KEYSTORE_FILE") ?: "absent.p12")
            storePassword System.getenv("KEYSTORE_PASS") ?: ""
            keyAlias "kajypay"
            keyPassword System.getenv("KEYSTORE_PASS") ?: ""
            storeType "pkcs12"
        }
    }
    buildTypes {
        debug { if (System.getenv("KEYSTORE_FILE") != null) signingConfig signingConfigs.stable }
        release {
            minifyEnabled false
            if (System.getenv("KEYSTORE_FILE") != null) signingConfig signingConfigs.stable
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
    implementation 'com.google.android.gms:play-services-code-scanner:16.1.0'
    implementation 'com.google.android.gms:play-services-base:18.5.0'
}
